# TiKV config template

[raftstore]
# set store capacity, if no set, use disk capacity.
capacity = "8G"

[coprocessor]
# When it is true, it will try to split a region with table prefix if
# that region crosses tables.
# split-region-on-table = false
# When the region's size exceeds region-max-size, we will split the region
# into two which the left region's size will be region-split-size or a little
# bit smaller.
# region-max-size = "144MB"
# region-split-size = "96MB"
# region-max-size = "2MB"
# region-split-size = "1MB"